### ISSUE TITLE
Bounce pads cancel horizontal momentum

### ISSUE THREAD

**Issue by TheDeviantCrafter** [przemykomo/effectpads#1]
I wanted to use jump and speed pads to create an elytra launcher. Unfortunately, touching a jump pads removes momentum from the player before shooting them in the air. If momentum was preserved, bounce pads could be used to make some fun contraptions.

In the below screenshot, I landed 6 blocks away whether I had a running start or not.

![2021-03-22_16 20 36](https://user-images.githubusercontent.com/18755309/112060000-9df68c00-8b2a-11eb-8537-cf9ab805e1ed.png)

**Comment by przemykomo** [comment]
Just tested it myself. It doesn't cancel horizontal momentum. Speed pads just aren't _that_ fast. I'd add higher tiers of speed pads if I knew how to fix the bug where you gain _really_ high speed when jumping over speed pads.
